[package]
name = "brocard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
approx = "*"
quickcheck = "*"
quickcheck_macros = "*"
rand = "*"
criterion = "*"
criterion-macro = "*"
